CLI: Don't allow update with older version unless forced
MetLifeLegalPlans/zygoat pull request #146
Opened 2021-04-26 17:18 UTC by knitHacker

closes #130

2021-04-26 17:27 UTC, cviveiro reviewed
this'll be great, it caused so many issues when we had one zg update that was out of order it was so hard to untangle in that pr and in fixes afterwards

2021-04-26 17:27 UTC, cviveiro commented on zygoat/cli.py
> +            return False
`return v1 < v2`

2021-04-26 17:27 UTC, cviveiro commented on zygoat/cli.py
> +        # do the business
lol, don't think we need this comment though

2021-04-26 17:27 UTC, cviveiro commented on zygoat/cli.py
> +        log.warn(
it seems from the log text that this should either get logged only if we're raising the exception, or you split it out and have a warning about the versions always and then only talk about using `--force` if someone hasn't?

2021-04-26 17:29 UTC, knitHacker commented on zygoat/cli.py
> +        # do the business
i removed the print statements, forgot the comments

2021-04-26 17:30 UTC, knitHacker commented on zygoat/cli.py
> +            return False
duhhh... i had different logic originally...

2021-04-26 17:30 UTC, knitHacker commented on zygoat/cli.py
> +            return False
wait no, i want it to continue in the loop if it is equal that is why it is like this

2021-04-26 17:40 UTC, knitHacker commented on zygoat/cli.py
> +        log.warn(
i think it should always warn even if it is forced so there is a record of the difference in versions

2021-04-26 17:41 UTC, knitHacker commented on zygoat/cli.py
> +        log.warn(
moved the suggestion to use `--force` into the exception message though

2021-04-26 18:10 UTC, knitHacker commented on zygoat/cli.py
> +            return False
i made the logic clearer (hopefully)

2021-04-26 18:46 UTC, cviveiro commented on zygoat/cli.py
> +            return False
you guessed what my next comment was going to be :)

2021-04-26 18:47 UTC, cviveiro approved these changes
lgtm! i'll wait until @markrawls can take a look in case he wants to

2021-04-26 20:03 UTC, markrawls requested changes
Just the one minor nit, but outside of that, it looks great!

2021-04-26 20:03 UTC, markrawls commented on zygoat/cli.py
> +    return False
There's probably a `semver` library for Python that lets us do easy comparisons without breaking it down ourselves

2021-04-26 20:39 UTC, knitHacker commented on zygoat/cli.py
> +    return False
will do. wasn't sure how conservative we were with adding new dependencies

2021-04-26 20:46 UTC, markrawls commented on zygoat/cli.py
> +    return False
Generally we leave it up to developer discretion. `left-pad` is something we want to avoid, using a standard version comparison library to compare versions is probably fine.

2021-04-28 17:28 UTC, knitHacker commented
@markrawls requested changes made

2021-04-28 22:01 UTC, markrawls approved these changes

2021-04-28 22:02 UTC, markrawls commented
Looks like you'll need to debug the dependencies - you used `poetry` to add them and update the lockfile, right?

2021-04-28 22:11 UTC, cviveiro commented
Oh, does the version need to get updated? Also in `pyproject.toml`

2021-04-29 13:19 UTC, knitHacker commented
my bad, first time using poetry so i had added the line to pyproject.toml myself. now used the poetry command so hopefully should work now

2021-04-29 19:03 UTC, knitHacker commented
wooooo checks passed @markrawls

2021-04-29 19:10 UTC, cviveiro commented
i do think we'll want to up the zygoat version number with this change, located here: https://github.com/MetLifeLegalPlans/zygoat/blob/df3ec42f623f925ee8dcc5b22c2a36e060d6402a/pyproject.toml#L3

2021-04-29 23:34 UTC, markrawls commented
(`poetry version patch`)

2021-05-03 18:00 UTC, cviveiro submitted a review, later dismissed

2021-05-03 18:56 UTC, cviveiro approved these changes

2021-05-03 18:56 UTC, merged