DOCKER: update containers to copy/cache dependencies
MetLifeLegalPlans/zygoat pull request #174
Opened 2022-03-07 19:13 UTC by kelarcrisp

closes #173 

on top of the dependency caching, I went ahead and changed a couple of places where we were using ADD to copy files over to use COPY instead. since all we're doing is copying local files over

2022-03-08 02:47 UTC, markrawls requested changes
We don't actually want to copy the source code over in the `.local` files - we want those to be populated via the `volume` mount in `docker-compose.yml` so that hot reloading works. Other than that, LGTM!

2022-03-08 17:48 UTC, kelarcrisp commented
ahh that makes sense. should be good now

2022-03-08 21:53 UTC, markrawls requested changes
Ah, sorry, one last change - we'll want to use `poetry install --no-dev` in the production Dockerfile so that we're not loading development dependencies.

2022-03-08 22:38 UTC, kelarcrisp commented
> Ah, sorry, one last change - we'll want to use `poetry install --no-dev` in the production Dockerfile so that we're not loading development dependencies.

@markrawls oh wow didn't realize that was a thing. I don't believe any of the other repos that have already been converted are doing this. I guess I'll go ahead and create issues in each repo do this as well?

2022-03-09 00:21 UTC, aricodes-oss approved these changes

2022-03-09 00:21 UTC, aricodes-oss approved these changes

2022-03-09 00:22 UTC, markrawls approved these changes

2022-03-09 00:22 UTC, merged